class_name Tiles

enum Flag {
  USESNEWDATA,
  ALIGNED,
  TREE,
  BUSH,
  NORMAL,
  MYCELIUM,
  ENCHANTED,
  GRASS,
  ROAD,
  FLATROAD,
  TUNDRA,
  CAVE,
  CAVEDOOR,
  VISIBLE_CAVEDOOR,
  SOLIDCAVE,
  REINFORCEDCAVE,
  ORECAVE,
  REINFORCEDFLOOR,
  BOTANIZE,
  FORAGE,
  BIRCH,
  PINE,
  OAK,
  CEDAR,
  WILLOW,
  MAPLE,
  APPLE,
  LEMON,
  OLIVE,
  CHERRY,
  CHESTNUT,
  WALNUT,
  FIR,
  LINDEN,
  LAVENDER,
  ROSE,
  THORN,
  GRAPE,
  CAMELLIA,
  OLEANDER,
  HAZELNUT,
  ORANGE,
  RASPBERRY,
  LINGONBERRY,
  BLUEBERRY
}

static var Type := {
  2: TileType.new(2, "Grass", "#366503", 0.75, "img.texture.terrain.grass", [Flag.GRASS, Flag.BOTANIZE, Flag.FORAGE], 60, 2, 1, 0),
  5: TileType.new(5, "Dirt", "#4B3F2F", 0.8, "img.texture.terrain.dirt", [0], 60, 2, 0, 0)
}
